# -*- coding: utf-8 -*-
"""Portfolio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VcPtnswoGp219OTm2LcWwhoNQcLTb1do
"""

from google.colab import drive

drive.mount('/content/drive')

os.listdir('/content/drive/MyDrive/AML_Project')

import pandas as pd

features = pd.read_csv(
    '/content/drive/MyDrive/AML_Project/elliptic_txs_features.csv',
    header=None
)

edges = pd.read_csv(
    '/content/drive/MyDrive/AML_Project/elliptic_txs_edgelist.csv'
)

classes = pd.read_csv(
    '/content/drive/MyDrive/AML_Project/elliptic_txs_classes.csv'
)

features.head()

!pip install pandas numpy matplotlib seaborn networkx

features.head()
features.shape

edges.head()

classes.head()
classes['class'].value_counts()

# Rename columns for clarity
features.rename(columns={0: "txId", 1: "time_step"}, inplace=True)

# Merge features + classes
df = features.merge(classes, on="txId", how="left")

df.head()

# Convert labels
df['class'] = df['class'].replace({
    'unknown': -1,
    '1': 1,
    '2': 0
})

df['class'].value_counts()

features.head()

features.shape

features.columns

features.rename(columns={
    0: "txId",
    1: "time_step"
}, inplace=True)

features.head()

df = features.merge(classes, on="txId", how="left")

df.head()

df.shape

df.isnull().sum()

df['class'].unique()

df['class'] = df['class'].replace({
    'unknown': -1,
    '1': 1,
    '2': 0
})

df['class'].value_counts()

df.info()

df.describe()

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='class', data=df)

plt.title("Transaction Class Distribution")
plt.xlabel("Class")
plt.ylabel("Count")

plt.show()

df['class'].value_counts(normalize=True) * 100

df[2].hist(bins=50)

plt.title("Feature 2 Distribution")
plt.xlabel("Feature Value")
plt.ylabel("Frequency")

plt.show()

licit_df = df[df['class'] == 0]
illicit_df = df[df['class'] == 1]
unknown_df = df[df['class'] == -1]

plt.figure(figsize=(10,5))

sns.kdeplot(licit_df[2], label='Licit')
sns.kdeplot(illicit_df[2], label='Illicit')

plt.title("Feature 2 Distribution: Licit vs Illicit")
plt.xlabel("Feature Value")
plt.ylabel("Density")

plt.legend()

plt.show()

features_to_check = [2, 3, 4, 5, 10]

for feature in features_to_check:

    plt.figure(figsize=(10,5))

    sns.kdeplot(licit_df[feature], label='Licit')
    sns.kdeplot(illicit_df[feature], label='Illicit')

    plt.title(f"Feature {feature}: Licit vs Illicit")
    plt.legend()

    plt.show()

plt.figure(figsize=(10,5))

sns.boxplot(x='class', y=2, data=df)

plt.title("Feature 2 by Transaction Class")

plt.show()

plt.figure(figsize=(12,8))

correlation = df.iloc[:, 0:20].corr()

sns.heatmap(correlation)

plt.title("Feature Correlation Heatmap")

plt.show()

import networkx as nx

G = nx.from_pandas_edgelist(
    edges,
    source='txId1',
    target='txId2',
    create_using=nx.DiGraph()
)

print("Number of nodes:", G.number_of_nodes())
print("Number of edges:", G.number_of_edges())

sample_nodes = list(G.nodes())[:100]

subgraph = G.subgraph(sample_nodes)

plt.figure(figsize=(12,12))

nx.draw(
    subgraph,
    node_size=50,
    with_labels=False
)

plt.title("Sample Transaction Network")

plt.show()

class_map = df.set_index('txId')['class'].to_dict()

node_colors = []

for node in subgraph.nodes():

    node_class = class_map.get(node, -1)

    if node_class == 1:
        node_colors.append('red')

    elif node_class == 0:
        node_colors.append('green')

    else:
        node_colors.append('gray')

plt.figure(figsize=(12,12))

nx.draw(
    subgraph,
    node_color=node_colors,
    node_size=50,
    with_labels=False
)

# Create legend
import matplotlib.patches as mpatches

red_patch = mpatches.Patch(color='red', label='Illicit')
green_patch = mpatches.Patch(color='green', label='Licit')
gray_patch = mpatches.Patch(color='gray', label='Unknown')

plt.legend(handles=[red_patch, green_patch, gray_patch])

plt.title("Transaction Network with Risk Labels")

plt.show()

degree_dict = dict(G.degree())

df['degree'] = df['txId'].map(degree_dict)

sns.boxplot(x='class', y='degree', data=df)

plt.title("Degree Distribution by Transaction Class")

plt.show()

df[['txId', 'class', 'degree']].sort_values(
    by='degree',
    ascending=False
).head(10)

subgraph_classes = []

for node in subgraph.nodes():
    subgraph_classes.append(class_map.get(node, -1))

pd.Series(subgraph_classes).value_counts()

illicit_tx = df[df['class'] == 1]['txId'].iloc[0]

illicit_tx

neighbors = list(G.neighbors(illicit_tx))

neighbors[:10]

small_nodes = [illicit_tx] + neighbors[:15]

small_subgraph = G.subgraph(small_nodes)

small_colors = []

for node in small_subgraph.nodes():

    node_class = class_map.get(node, -1)

    if node_class == 1:
        small_colors.append('red')

    elif node_class == 0:
        small_colors.append('green')

    else:
        small_colors.append('gray')

plt.figure(figsize=(10,10))

nx.draw(
    small_subgraph,
    node_color=small_colors,
    with_labels=True,
    node_size=300,
    font_size=8
)

plt.title("Focused Network Around an Illicit Transaction")

plt.show()

illicit_neighbor_count = {}

for node in G.nodes():

    neighbors = list(G.neighbors(node))

    illicit_count = 0

    for neighbor in neighbors:

        if class_map.get(neighbor) == 1:
            illicit_count += 1

    illicit_neighbor_count[node] = illicit_count

df['illicit_neighbors'] = df['txId'].map(illicit_neighbor_count)

df[['txId', 'class', 'illicit_neighbors']].sort_values(
    by='illicit_neighbors',
    ascending=False
).head(20)

df[df['class'] == -1][
    ['txId', 'illicit_neighbors']
].sort_values(
    by='illicit_neighbors',
    ascending=False
).head(20)

df['risk_score'] = (
    df['illicit_neighbors'] * 50
)

df[
    ['txId', 'class', 'illicit_neighbors', 'risk_score']
].sort_values(
    by='risk_score',
    ascending=False
).head(20)

def classify_risk(score):

    if score >= 100:
        return "High Risk"

    elif score >= 50:
        return "Medium Risk"

    else:
        return "Low Risk"

df['risk_level'] = df['risk_score'].apply(classify_risk)

df['risk_level'].value_counts()

df[
    (df['class'] == -1) &
    (df['risk_level'] == 'High Risk')
][
    ['txId', 'illicit_neighbors', 'risk_score']
].head(20)

import random

sample_nodes = random.sample(list(G.nodes()), 5000)

sample_graph = G.subgraph(sample_nodes)

betweenness = nx.betweenness_centrality(
    sample_graph,
    normalized=True
)

df['betweenness'] = df['txId'].map(betweenness)

df['betweenness'] = df['betweenness'].fillna(0)

df[
    ['txId', 'class', 'betweenness']
].sort_values(
    by='betweenness',
    ascending=False
).head(20)

df['betweenness_scaled'] = (
    df['betweenness'] * 1000000
)

df['advanced_risk_score'] = (

    df['illicit_neighbors'] * 50

    + df['degree'] * 2

    + df['betweenness_scaled'] * 10
)

df[
    [
        'txId',
        'class',
        'illicit_neighbors',
        'degree',
        'betweenness_scaled',
        'advanced_risk_score'
    ]
].sort_values(
    by='advanced_risk_score',
    ascending=False
).head(20)

df['improved_risk_score'] = (

    df['illicit_neighbors'] * 100

    + (
        df['degree']
        * df['illicit_neighbors']
        * 2
    )

    + (
        df['betweenness_scaled']
        * df['illicit_neighbors']
        * 5
    )
)

df[
    [
        'txId',
        'class',
        'illicit_neighbors',
        'degree',
        'betweenness_scaled',
        'improved_risk_score'
    ]
].sort_values(
    by='improved_risk_score',
    ascending=False
).head(20)

high_risk_unknowns = df[
    (df['class'] == -1) &
    (df['improved_risk_score'] > 0)
]

high_risk_unknowns[
    [
        'txId',
        'illicit_neighbors',
        'degree',
        'betweenness_scaled',
        'improved_risk_score'
    ]
].sort_values(
    by='improved_risk_score',
    ascending=False
).head(10)

target_tx = high_risk_unknowns.sort_values(
    by='improved_risk_score',
    ascending=False
)['txId'].iloc[0]

target_tx

target_neighbors = list(G.neighbors(target_tx))

target_neighbors[:20]

investigation_nodes = [target_tx] + target_neighbors

investigation_graph = G.subgraph(investigation_nodes)

investigation_colors = []

for node in investigation_graph.nodes():

    node_class = class_map.get(node, -1)

    if node_class == 1:
        investigation_colors.append('red')

    elif node_class == 0:
        investigation_colors.append('green')

    else:
        investigation_colors.append('gray')

plt.figure(figsize=(12,12))

nx.draw(
    investigation_graph,
    node_color=investigation_colors,
    with_labels=True,
    node_size=400,
    font_size=8
)

plt.title("Suspicious Unknown Transaction Investigation")

plt.show()

"""# Executive Summary

This project investigates the use of graph analytics and risk scoring techniques to identify potentially suspicious Bitcoin transactions associated with illicit activity.

Using the Elliptic Bitcoin Dataset, transaction relationships were modeled as a directed network in which transactions interact through flows of cryptocurrency. Exploratory analysis, graph metrics, and rule-based AML scoring techniques were applied to evaluate how proximity to illicit activity and structural importance within the network may increase transaction risk.

The analysis identified several unknown transactions with elevated exposure to illicit nodes, suggesting that graph-based approaches can support AML investigators in prioritizing suspicious activity for further review.

This project demonstrates how network analytics can enhance traditional transaction monitoring by incorporating relationship-based risk signals into AML investigations.

# Business Problem

Financial institutions and cryptocurrency platforms face increasing challenges in identifying transactions potentially associated with money laundering and illicit financial activity.

Traditional AML monitoring systems often focus on isolated transaction behavior, which may fail to detect suspicious relationships hidden within complex transaction networks. In cryptocurrency ecosystems, illicit funds frequently move through multiple intermediary transactions, making detection more difficult through traditional rule-based approaches alone.

This project investigates whether graph-based network analysis can support AML investigations by identifying unknown Bitcoin transactions with elevated exposure to illicit activity.

By combining transaction behavior, network connectivity, and graph centrality metrics, the analysis aims to prioritize suspicious unknown transactions for further investigative review.

# Dataset Description

This project uses the Elliptic Bitcoin Dataset, a publicly available cryptocurrency transaction dataset designed for financial crime and AML research.

The dataset models Bitcoin transactions as a directed graph network, where:

- Nodes represent individual Bitcoin transactions
- Edges represent the flow of Bitcoin between transactions

The dataset contains three primary components:

### Transaction Features
A set of anonymized numerical features describing transaction behavior and structural blockchain characteristics.

### Transaction Classes
Labels identifying transactions as:
- Licit (legitimate activity)
- Illicit (known suspicious or criminal activity)
- Unknown (unlabeled transactions)

### Transaction Edges
Relationships between transactions representing transaction flow connections within the Bitcoin network.

The dataset contains over 200,000 transactions, including a relatively small percentage of illicit activity, reflecting the highly imbalanced nature of real-world AML detection problems.

# Methodology

The analysis was conducted using Python within a Google Colab environment. Data preprocessing, exploratory analysis, graph modeling, and risk scoring techniques were applied throughout the investigation.

The methodology included the following stages:

1. Data loading and preprocessing
   - Merging transaction features, labels, and network relationships
   - Cleaning and standardizing class labels

2. Exploratory Data Analysis (EDA)
   - Evaluating transaction class distribution
   - Comparing behavioral feature distributions between licit and illicit transactions
   - Identifying class imbalance patterns

3. Graph Network Construction
   - Modeling Bitcoin transactions as a directed graph using NetworkX
   - Representing transaction relationships through node-edge structures

4. Network Risk Analysis
   - Measuring illicit transaction proximity
   - Calculating degree and betweenness centrality metrics
   - Evaluating structural influence within the transaction network

5. Rule-Based AML Risk Scoring
   - Combining network exposure and graph metrics into a weighted risk scoring framework
   - Prioritizing unknown transactions with elevated suspicious exposure

# Exploratory Analysis Findings

Initial exploratory analysis revealed a significant class imbalance within the dataset. Illicit transactions represented only a small fraction of the total transaction population, while the majority of transactions remained unlabeled.

This distribution reflects a common challenge in AML investigations, where suspicious activity is rare relative to overall transaction volume.

Comparative analysis between licit and illicit transactions showed differences in several anonymized transaction features, suggesting that certain behavioral characteristics may vary between legitimate and suspicious activity.

However, substantial overlap between classes also demonstrated the limitations of relying solely on isolated transaction behavior for AML detection.

# Graph Analysis Findings

Graph-based analysis revealed that transaction relationships provided additional investigative context beyond isolated transaction features.

By modeling transactions as a directed network, it became possible to evaluate how suspicious exposure may propagate through connected transaction paths.

Several unknown transactions were identified with direct connections to illicit nodes, indicating elevated exposure to suspicious activity despite lacking explicit illicit classification.

Network metrics such as degree and betweenness centrality further highlighted structurally influential transactions that may play intermediary roles within transaction flows.

# Risk Scoring Findings

A rule-based AML risk scoring framework was developed by combining multiple network-based indicators, including:

- proximity to illicit transactions
- transaction connectivity
- graph centrality metrics

Initial scoring approaches generated elevated risk scores for several highly connected licit transactions, demonstrating the importance of model calibration and contextual interpretation within AML systems.

The scoring methodology was subsequently refined to prioritize network influence only when suspicious illicit exposure was also present.

The final framework successfully identified unknown transactions with elevated network-based risk characteristics, supporting the use of graph analytics for AML investigative prioritization.

# Recommendations

The results of this analysis suggest that graph-based transaction monitoring may provide valuable support for AML investigative workflows within cryptocurrency environments.

The following operational recommendations are proposed:

### Enhanced Monitoring of High-Risk Unknown Transactions
Unknown transactions with elevated exposure to illicit activity should be prioritized for additional monitoring and investigative review.

### Integration of Graph Analytics into AML Systems
Traditional transaction monitoring systems may benefit from incorporating relationship-based indicators such as:
- illicit transaction proximity
- network centrality
- transaction connectivity patterns

### Risk-Based Alert Prioritization
Graph-derived risk indicators may help reduce investigative overload by improving alert prioritization and focusing analyst attention on structurally suspicious activity.

### Continuous Model Calibration
AML risk models should be continuously refined to reduce false positives and improve contextual interpretation of highly connected legitimate entities such as exchanges and payment hubs.

# Limitations and Future Improvements

This analysis contains several limitations that should be considered when interpreting the results.

The Elliptic dataset contains anonymized transaction features, limiting direct interpretation of underlying transaction behavior and preventing access to real-world customer or wallet identity information.

Additionally, the risk scoring framework was rule-based and designed primarily for investigative prioritization rather than predictive classification accuracy.

Future improvements could include:
- machine learning-based risk modeling
- community detection and cluster analysis
- temporal transaction pattern analysis
- wallet-level aggregation techniques
- real-time transaction monitoring frameworks

Further research may also explore how graph neural networks and advanced blockchain analytics techniques could improve AML detection capabilities within cryptocurrency ecosystems.

# Final Investigation Summary

The investigation identified several unknown Bitcoin transactions exhibiting elevated exposure to illicit activity through graph-based transaction relationships.

By combining transaction proximity, network connectivity, and structural graph metrics, the analysis demonstrated how suspicious exposure may propagate beyond explicitly labeled illicit transactions.

A focused investigation subgraph revealed unknown transactions directly connected to multiple illicit nodes, suggesting elevated AML risk despite the absence of confirmed illicit classification.

The project highlights the value of graph analytics as a complementary AML investigative tool capable of improving suspicious activity prioritization within cryptocurrency transaction networks.
"""